CODE55_CLASSES = {
    "Chair",
    "Table",
    "TV",
    "Washing Machine",
    "Cabinet",
    "Gaming Console",
    "Sofa",
    "Speaker",
    "Fireplace",
    "Bed",
    "Wardrobe",
    "Pillow",
    "Nightstand",
    "Bathtub",
    "Toilet",
    "Shower",
    "Laundry Rack",
    "Hair Dryer",
    "Fridge",
    "Microwave",
    "Dishwasher",
    "Stove",
    "Kettle",
    "Coffe Machine",
    "Toaster",
    "Oven",
    "Lamp",
    "Air Conditioning",
    "Computer",
    "Plant",
    "Window",
    "Desk",
    "Door",
    "Mirror",
    "Socket",
    "Sink",
    "Aquarium",
    "Painting",
    "Air Purifier",
    "Switch",
    "Boiler",
    "Rug",
    "Board",
    "Vase",
    "Faucet",
    "Curtain",
    "Roller Blind",
    "Shelf",
    "Fire Extinguisher",
    "Fan",
    "Heater",
    "Car",
    "Phone",
    "Clock",
    "Alarm Sensor"
}
